#define TERRAIN_CHUNK_OFFSET 16
#define TERRAIN_CHUNK_WIDTH 64
#define TERRAIN_CHUNK_HEIGHT 64
#define TERRAIN_CHUNK_COUNT_WIDTH 1024 / TERRAIN_CHUNK_WIDTH
#define TERRAIN_CHUNK_COUNT_HEIGHT 1024 / TERRAIN_CHUNK_HEIGHT
